name: Request Unity Activation File

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  request-alf:
    name: Request .alf file
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-request-activation-file@65874ef791dae6dfa5829f1cb490eafbd7b2173c # v2
        id: getManualLicenseFile

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: unity-activation-file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
          retention-days: 1
